import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import {
  arrayMove, SortableContext, sortableKeyboardCoordinates,
  useSortable, verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { Button } from "@/components/ui/button";
import {
  GitBranch, Hammer, ShieldCheck, Rocket, GripVertical, Plus, Trash2,
  Download, Copy, ArrowLeft, Check,
} from "lucide-react";
import { Link } from "react-router-dom";
import { useToast } from "@/hooks/use-toast";

interface BuilderStage {
  id: string;
  name: string;
  provider: string;
  icon: "source" | "build" | "approve" | "deploy";
  buildspec?: string;
}

const iconMap = {
  source: GitBranch,
  build: Hammer,
  approve: ShieldCheck,
  deploy: Rocket,
};

const presets: Omit<BuilderStage, "id">[] = [
  { name: "Source", provider: "GitHub", icon: "source" },
  { name: "Build", provider: "CodeBuild", icon: "build" },
  { name: "Test", provider: "CodeBuild", icon: "build" },
  { name: "Approval", provider: "Manual gate", icon: "approve" },
  { name: "Deploy to Dev", provider: "CodeDeploy · EC2", icon: "deploy" },
  { name: "Deploy to Prod", provider: "CodeDeploy · EC2", icon: "deploy" },
];

const defaultStages: BuilderStage[] = [
  { id: "1", name: "Source", provider: "GitHub · main", icon: "source" },
  { id: "2", name: "Build", provider: "CodeBuild", icon: "build" },
  { id: "3", name: "Deploy", provider: "CodeDeploy · EC2", icon: "deploy" },
];

function generateYAML(stages: BuilderStage[]): string {
  const lines: string[] = [
    "# Generated by DeployOps Pipeline Builder",
    "# AWS CodePipeline configuration",
    "",
    "pipeline:",
    "  name: webapp-pipeline",
    "  roleArn: arn:aws:iam::role/CodePipelineRole",
    "  stages:",
  ];

  stages.forEach((s, i) => {
    lines.push(`    - name: ${s.name}`);
    lines.push(`      order: ${i + 1}`);

    if (s.icon === "source") {
      lines.push("      actions:");
      lines.push("        - name: SourceAction");
      lines.push("          actionTypeId:");
      lines.push("            category: Source");
      lines.push("            owner: ThirdParty");
      lines.push("            provider: GitHub");
      lines.push("            version: '2'");
      lines.push("          configuration:");
      lines.push("            Owner: your-org");
      lines.push("            Repo: your-repo");
      lines.push("            Branch: main");
      lines.push("            OAuthToken: '{{resolve:secretsmanager:github-token}}'");
    } else if (s.icon === "build") {
      lines.push("      actions:");
      lines.push("        - name: BuildAction");
      lines.push("          actionTypeId:");
      lines.push("            category: Build");
      lines.push("            owner: AWS");
      lines.push("            provider: CodeBuild");
      lines.push("            version: '1'");
      lines.push("          configuration:");
      lines.push("            ProjectName: webapp-build");
      lines.push("          inputArtifacts:");
      lines.push("            - name: SourceOutput");
    } else if (s.icon === "approve") {
      lines.push("      actions:");
      lines.push("        - name: ManualApproval");
      lines.push("          actionTypeId:");
      lines.push("            category: Approval");
      lines.push("            owner: AWS");
      lines.push("            provider: Manual");
      lines.push("            version: '1'");
      lines.push("          configuration:");
      lines.push("            NotificationArn: arn:aws:sns::topic/approvals");
    } else if (s.icon === "deploy") {
      lines.push("      actions:");
      lines.push("        - name: DeployAction");
      lines.push("          actionTypeId:");
      lines.push("            category: Deploy");
      lines.push("            owner: AWS");
      lines.push("            provider: CodeDeploy");
      lines.push("            version: '1'");
      lines.push("          configuration:");
      lines.push("            ApplicationName: webapp");
      lines.push("            DeploymentGroupName: webapp-dg");
      lines.push("          inputArtifacts:");
      lines.push("            - name: BuildOutput");
    }
    lines.push("");
  });

  return lines.join("\n");
}

const SortableStage = ({ stage, onRemove }: { stage: BuilderStage; onRemove: () => void }) => {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: stage.id,
  });
  const Icon = iconMap[stage.icon];

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    zIndex: isDragging ? 50 : undefined,
    opacity: isDragging ? 0.8 : 1,
  };

  return (
    <motion.div
      ref={setNodeRef}
      style={style}
      layout
      className="flex items-center gap-3 rounded-xl border border-border bg-card-gradient p-4 shadow-card group"
    >
      <button {...attributes} {...listeners} className="cursor-grab active:cursor-grabbing text-muted-foreground hover:text-foreground">
        <GripVertical className="h-4 w-4" />
      </button>
      <div className="rounded-lg bg-background/60 p-2 border border-border">
        <Icon className="h-4 w-4 text-primary" />
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-foreground">{stage.name}</p>
        <p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{stage.provider}</p>
      </div>
      <Button
        variant="ghost"
        size="icon"
        className="h-7 w-7 opacity-0 group-hover:opacity-100 transition-opacity text-destructive"
        onClick={onRemove}
      >
        <Trash2 className="h-3.5 w-3.5" />
      </Button>
    </motion.div>
  );
};

const PipelineBuilder = () => {
  const [stages, setStages] = useState<BuilderStage[]>(defaultStages);
  const [yaml, setYaml] = useState<string>(generateYAML(defaultStages));
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates })
  );

  const handleDragEnd = useCallback((event: DragEndEvent) => {
    const { active, over } = event;
    if (over && active.id !== over.id) {
      setStages((prev) => {
        const oldIdx = prev.findIndex((s) => s.id === active.id);
        const newIdx = prev.findIndex((s) => s.id === over.id);
        const updated = arrayMove(prev, oldIdx, newIdx);
        setYaml(generateYAML(updated));
        return updated;
      });
    }
  }, []);

  const addStage = (preset: Omit<BuilderStage, "id">) => {
    const id = Date.now().toString();
    setStages((prev) => {
      const updated = [...prev, { ...preset, id }];
      setYaml(generateYAML(updated));
      return updated;
    });
  };

  const removeStage = (id: string) => {
    setStages((prev) => {
      const updated = prev.filter((s) => s.id !== id);
      setYaml(generateYAML(updated));
      return updated;
    });
  };

  const downloadYAML = () => {
    const blob = new Blob([yaml], { type: "text/yaml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "pipeline.yml";
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Downloaded", description: "pipeline.yml saved to your device" });
  };

  const copyYAML = async () => {
    await navigator.clipboard.writeText(yaml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({ title: "Copied", description: "YAML copied to clipboard" });
  };

  return (
    <div className="min-h-screen text-foreground">
      <header className="border-b border-border/60 bg-background/70 backdrop-blur-md sticky top-0 z-30">
        <div className="container flex items-center justify-between py-4">
          <div className="flex items-center gap-3">
            <Link to="/">
              <Button variant="ghost" size="icon" className="h-9 w-9">
                <ArrowLeft className="h-4 w-4" />
              </Button>
            </Link>
            <div>
              <h1 className="text-lg font-semibold tracking-tight">Pipeline Builder</h1>
              <p className="font-mono text-[11px] text-muted-foreground">drag · drop · export YAML</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" className="gap-1.5" onClick={copyYAML}>
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? "Copied" : "Copy YAML"}
            </Button>
            <Button size="sm" className="gap-1.5 ring-glow" onClick={downloadYAML}>
              <Download className="h-3.5 w-3.5" /> Export YAML
            </Button>
          </div>
        </div>
      </header>

      <main className="container py-8">
        <div className="grid gap-6 lg:grid-cols-2">
          {/* Stages panel */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
                Pipeline stages ({stages.length})
              </h2>
            </div>

            <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
              <SortableContext items={stages.map((s) => s.id)} strategy={verticalListSortingStrategy}>
                <div className="space-y-2">
                  <AnimatePresence>
                    {stages.map((stage) => (
                      <SortableStage key={stage.id} stage={stage} onRemove={() => removeStage(stage.id)} />
                    ))}
                  </AnimatePresence>
                </div>
              </SortableContext>
            </DndContext>

            {/* Add stage presets */}
            <div className="rounded-xl border border-dashed border-border p-4 space-y-3">
              <p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
                Add stage
              </p>
              <div className="flex flex-wrap gap-2">
                {presets.map((p, i) => {
                  const Icon = iconMap[p.icon];
                  return (
                    <Button
                      key={i}
                      variant="outline"
                      size="sm"
                      className="gap-1.5 text-xs"
                      onClick={() => addStage(p)}
                    >
                      <Plus className="h-3 w-3" />
                      <Icon className="h-3 w-3" />
                      {p.name}
                    </Button>
                  );
                })}
              </div>
            </div>
          </div>

          {/* YAML preview */}
          <div className="rounded-xl border border-border bg-card-gradient shadow-card overflow-hidden">
            <div className="flex items-center justify-between border-b border-border bg-background/40 px-4 py-2.5">
              <span className="font-mono text-xs uppercase tracking-wider text-foreground">pipeline.yml</span>
              <div className="flex items-center gap-1.5">
                <span className="h-2 w-2 rounded-full bg-destructive/70" />
                <span className="h-2 w-2 rounded-full bg-warning/70" />
                <span className="h-2 w-2 rounded-full bg-primary/70" />
              </div>
            </div>
            <pre className="p-4 font-mono text-[12px] leading-relaxed text-foreground/90 overflow-auto max-h-[600px] scanlines">
              {yaml}
            </pre>
          </div>
        </div>
      </main>
    </div>
  );
};

export default PipelineBuilder;
